[package]
version = "1.0.0"
name = "wordle_solver"
authors = ["Simon Gomizelj"]
description = "Wordle Solver"
license = "Unlicense"
readme = "../README.md"
repository = "https://github.com/vodik/wordle-app"
edition = "2021"

[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[lib]
crate-type = ["cdylib"]

[dependencies]
js-sys = "0.3"
wasm-bindgen = "0.2"
